### PR TITLE
Feature/v2 upgrade & Grouping support

### PR DESCRIPTION
**Pull request by sirkirby**
Upgrade to support Serilog v2 and added custom grouping support.

### CODE REVIEW

**Comment by sirkirby** [comment]
@tony-haupt I've forked and modified this Sink to support v2 of Serilog and I've also added the custom group key support that you added to Raygun.Diagnostics. Can you review this implementation for comparison?

**Comment by tony-haupt** [comment]
Implementation looks good.  You're binding the custom event to the RayGunClient prior to sending the message and in the event itself you're using the proper CustomGroupingKey property of the event arguments.

**Review by tony-haupt — APPROVED** [review]

**Comment by sirkirby** [comment]
@tony-haupt any thoughts? I've made some changes based on my testing and the raygun samples.. I think we may want to make similar changes to Raygun.Diagnostics as well. With that said. I still can't get this to work.. no matter what I try, all of the errors are not getting grouped on Raygun. I've verified that the group is coming through, however I've not been able to debug to verify the event is actually firing. I would assume it is though. Here is my sample code... it is posting the the Adapt Bot raygun application

```csharp
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .WriteTo.Raygun("ht//yCo7AwRdQnVj5zjkog==", tags: new[] { "chicken", "beef", "misc"})
    .WriteTo.Console()
    .CreateLogger();

  var transaction = new { TransactionId = Guid.NewGuid()};
  var myLog = Log.ForContext("Transaction", transaction, true).ForContext("GroupKey", "mycustomkey");  
  
  myLog.Information("This is highlevel trace information");  
  myLog.Debug("This is low level diagnostic information");  
  myLog.Error(new Exception("unexpected error"), "This is unexpected error information");
  myLog.Error(new Exception("expected error"), "This is expected error information");
  myLog.Error(new Exception("random error"), "This is random error information");
```

**Comment by sirkirby** [comment]
@tony-haupt ok, got rid of all of the event code and added new custom tags per log event. All have tested well and the code is much simpler. Here is new sample:

```csharp
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .WriteTo.Raygun("ht//yCo7AwRdQnVj5zjkog==", tags: new[] { "chicken", "beef"})
    .WriteTo.Console()
    .CreateLogger();    

  var transaction = new { TransactionId = Guid.NewGuid()};
  var myLog = Log.ForContext("Transaction", transaction, true).ForContext("GroupKey", "mycustomkey");  
  
  myLog.Information("This is highlevel trace information");
  myLog.Debug("This is low level diagnostic information");
  myLog.ForContext("Tags", new[] {"tag1", "tag2"}).Error(new Exception("unexpected error"), "This is unexpected error information");
  myLog.Error(new Exception("expected error"), "This is expected error information {@Tags}", new[] {"tag3", "tag4"});
  myLog.Error(new Exception("random error"), "This is random error information");
```

fyi.. the raygun app key has been reset... since this is all oss :)

**Pull request merged**
